[package]
name = "ori-rando-installer"
version = "0.1.0"
edition = "2024"

[dependencies]
memchr = "2.7.4"
regex = { version = "1.11.1", default-features = false, features = ["std", "perf"] }
windows-sys = { version = "0.59.0", features = ["Win32_UI_WindowsAndMessaging", "Win32_System_Memory"] }
winreg = "0.55.0"
